# Example Home Assistant Script Blueprint
blueprint:
  name: Example Notification Script
  description: Send a notification to a user.
  domain: script
  input:
    notify_target:
      name: Notify Target
      selector:
        entity:
          domain: notify
    message:
      name: Message
      selector:
        text:
trigger: []
action:
  - service: notify.notify
    data:
      target: !input notify_target
      message: !input message
mode: single
