# Luau Themed Lighting Automation Blueprint
blueprint:
  name: Luau Themed Lighting
  description: >
    Create a Luau party atmosphere by slowly cycling multiple RGB lights through tropical colors. Trigger with a button or dashboard event.
  domain: automation
  input:
    target_lights:
      name: RGB Lights
      description: Select one or more RGB lights to use for the Luau effect.
      selector:
        target:
          entity:
            domain: light
    cycle_delay:
      name: Color Change Delay
      description: Time (in seconds) between color changes.
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: seconds
    repeat_count:
      name: Number of Color Cycles
      description: How many times to cycle through the color palette.
      default: 10
      selector:
        number:
          min: 1
          max: 100
  source_url: https://github.com/mirkop/hass-blueprints
trigger:
  - platform: event
    event_type: luau_lighting_start
    # Trigger this event from a dashboard button or automation
condition: []
action:
  - variables:
      colors:
        - [255, 94, 77]    # Coral
        - [255, 195, 0]    # Yellow
        - [0, 255, 164]    # Aqua
        - [0, 122, 255]    # Blue
        - [255, 0, 191]    # Magenta
        - [255, 102, 255]  # Orchid
        - [0, 255, 255]    # Teal
  - repeat:
      count: !input repeat_count
      sequence:
        - choose:
            - conditions: []
              sequence:
                - service: light.turn_on
                  target: !input target_lights
                  data:
                    rgb_color: "{{ colors[repeat.index % colors|length] }}"
                    brightness: 200
                - delay:
                    seconds: !input cycle_delay
mode: single

# Usage:
# - Add a button to your dashboard that fires the event 'luau_lighting_start' to trigger this automation.
# - Adjust the color palette, delay, and repeat count as desired.
